[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "bluesky_mcp"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "mcp",
    "atproto"
]

[tool.hatch.build.targets.wheel]
packages = ["src/bluesky_mcp"]